### ISSUE TITLE
[HXSound] SoundPool slight cut the end of sound when playing looped.

### ISSUE THREAD

**Issue by TheMaxCoder** [huhx0015/HXAudioPlayer#10]
First of all great work :) 

When we play bit larger sounds (10 sec - 20 sec) with SoundPool, it slight cut the ending of sound by roughly 500-1000ms. Any ideas how we can solve this issue?
I know this is not the issue of your lib but I thought I would discuss it with you if we can have a solution.

Another thing I would like to discuss when playing gapless with `HXMusic`, Everytime `onCompletion` is called, the app takes a slight performance hit because we are creating a new MediaPlayer there. 
Any ideas on how we can avoid it?

Thanks a lot for your time.
Max

**Comment by huhx0015** [comment]
Hi @TheMaxCoder,

Sorry for getting back to you so late, I did not see your issue until now. Regarding the use of HXSound with longer audio files, since HXAudioPlayer relies on SoundPool, it is still bound by the same 1 MB memory buffer limitations.  The `HXSound` component should only be used to play audio files up to 5 sec. See more references here:

https://stackoverflow.com/questions/7141863/how-to-prevent-soundpool-from-truncating-sounds
https://stackoverflow.com/questions/13377604/soundpool-plays-only-first-5-secs-of-file-why 

For longer audio files, I recommend using the `HXMusic` instead, with the `.looped(false)` attribute.

Regarding gapless playback, HXAudioPlayer uses a dual MediaPlayer solution to simulate gapless audio playback. Using the `.looped(true)` attribute instead of '.gapless(true)` will fall back to the standard (single-only) MediaPlayer looping playback. However, this solution won't be ideal for gapless audio, as MediaPlayer's `setLooping()` often skips audio on many devices. 

I will look into ways of reducing the performance hit when `onCompletion` is called; might need to offload this to a separate thread.

**Comment by huhx0015** [comment]
The issue of sound effects being cut off has been resolved with the following commit:

https://github.com/huhx0015/HXAudioPlayer/commit/4749c49d7baf5d3bb19385b24e5e675e70d6ec56

The latest release of HXAudioPlayer `3.3.1` contains the fix for this issue: https://github.com/huhx0015/HXAudioPlayer/releases/tag/v3.3.1
